- project:
    check: &jobs
      jobs:
        - shake-factory-npm-rpmbuild:
            required-projects:
              - software-factory/re-sf
              - software-factory/re-patternfly
    gate: *jobs
