- project:
    check: &jobs
      jobs:
        - pnpm-rpmbuild:
            required-projects:
              - software-factory/re-sf
              - software-factory/re-patternfly
              - software-factory/res-remoteapi
            vars:
              scratch_build: false
              pnpm_install: "--shamefully-hoist"
