- project:
    check: &jobs
      jobs:
        - pnpm-test:
            required-projects:
              - software-factory/re-sf
              - software-factory/re-patternfly
              - software-factory/res-remoteapi
        - pnpm-rpmbuild:
            required-projects:
              - software-factory/re-sf
              - software-factory/re-patternfly
              - software-factory/res-remoteapi
            vars:
              pnpm_install: "--shamefully-hoist"
    gate: *jobs
    release:
      jobs:
        - pnpm-rpm-publish:
            required-projects:
              - software-factory/re-sf
              - software-factory/re-patternfly
            vars:
              scratch_build: false
              pnpm_install: "--shamefully-hoist"
