- project:
    check: &jobs
      jobs:
        - npm-test:
            required-projects:
              - software-factory/re-sf
              - software-factory/re-patternfly
    gate: *jobs
    release:
      jobs:
        - npm-rpm-publish:
            required-projects:
              - software-factory/re-sf
              - software-factory/re-patternfly
            vars:
              scratch_build: false
