- project:
    check: &jobs
      jobs:
        - pnpm-rpmbuild:
            required-projects:
              - software-factory/re-sf
              - software-factory/re-patternfly
            vars:
              scratch_build: false
              pnpm_install: "--shamefully-hoist"
