- project:
    check: &jobs
      jobs:
        - pnpm-test:
            required-projects:
              - software-factory/re-sf
              - software-factory/re-patternfly
              - software-factory/res-remoteapi
    gate: *jobs
    # uncomment when job is ready
    # release:
    #   jobs:
    #     - pnpm-rpm-publish:
    #         required-projects:
    #           - software-factory/re-sf
    #           - software-factory/re-patternfly
    #         vars:
    #           scratch_build: false
    #           pnpm_install: "--shamefully-hoist"
